# Generated by Django 2.2.2 on 2019-06-16 20:03

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pCond', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=1000, size=None)),
                ('attributes', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=1000, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('availableRepairs', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=10000, size=None)),
                ('preferedness', models.IntegerField()),
                ('tup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacleaner.Tuple')),
            ],
        ),
    ]
